### ISSUE TITLE
Some manifests cause crash 

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-annotation-editor#109]
This manifest can break MAE only in beeing in the manifest catalog.

"https://dzkimgs.l.u-tokyo.ac.jp/videos/iiif_in_japan_2017/manifest.json"

I think it is the old manifest format 

To reproduce : 

- Open stock MAE
- Open a manifest 
- Click on x in top left

App crash on manifest.js L142

![image](https://github.com/user-attachments/assets/92051470-695c-47a4-b023-66015f6acc39)

![image](https://github.com/user-attachments/assets/4eb96b2d-69ce-465e-9ec4-ec578bd31fa1)

**Comment by geourjoa** [comment]
Bug come manifesto and IIIFResources.js

I dont know why error break mae and not Mirador Stock

![image](https://github.com/user-attachments/assets/dc82cd92-04ce-4602-a2e8-1e0b95c867b6)

**Comment by geourjoa** [comment]
I don't lose more time on it, I only remove this breaking manifest from default catalog.

**Comment by daxid** [comment]
Yes @geourjoa Lets keep this open and see if we figure out what's going on.

The Manifest is announced as using Presentation API v3 (the last) so it should not be considered as an "old" manifest.

Could the japanese characters inside it be the reason ?

**Comment by geourjoa** [comment]
I dont know why but now same error are breaking mirador video

![image](https://github.com/user-attachments/assets/20536cf6-ad05-4a53-9885-072169616aab)

**Comment by geourjoa** [comment]
Ok, i have a lead

I downgrade manifesto.js 4.20.20 to 4.20.17 and i seem to work

https://www.npmjs.com/package/manifesto.js?activeTab=versions

**Comment by geourjoa** [comment]
I need also to force the addition of multiple package.

```sh
npm install react-sizeme
npm i @babel/plugin-proposal-private-property-in-object
npm i @babel/plugin-proposal-object-rest-spread
npm i
```

I use currently node 18 on this project
