### ISSUE TITLE
Error on MAE integration with MMU

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#119]
- [ ] On reload, the workspace exported by mmu and saved in bd is set with localStorageAdapter, or MAE use localStorage by default when no other storage are set. 
- [ ] When creating an annotation the get routes from adapter is not call, so the annotation doesn't render on the left panel

**Comment by geourjoa** [comment]
@Drilio On the second point, can you confirm you have the good comportment with LocalStorage

**Comment by geourjoa** [comment]
> * [ ]  On reload, the workspace exported by mmu and saved in bd is set with localStorageAdapter, or MAE use localStorage by default when no other storage are set.

@Drilio 
When reopening project can you precise if Mirador Config Adapter is not set or if its set with LocalStorageAdapter  ?

**Comment by Drilio** [comment]
I would say it's not set but can't be sure of this

**Comment by geourjoa** [comment]
No more relevant
