### ISSUE TITLE
Annotate images (not videos)

### ISSUE THREAD

**Issue by daxid** [SCENE-CE/mirador-annotation-editor#28]
Right now the annotation on images are not saved

**Comment by daxid** [comment]
I made a test image manifest with annotations : https://files.tetras-libre.fr/dev/annotatedImageManifest/manifestWithAnnotationTemplates_image_MAE.json

The only annotation templates that should appear in the beta release are :

- Note
- Tag
- Expert mode

All the other are not relevant as Mirador is not displaying anything except the target.

The Image template could be relevant but should have the motivation painting so the image is displayed (to be double-checked) -> then what happens to the note the is present in all annotation templates ? 

The Document template could be relevant WITH OUR FORK.

@geourjoa  How will we detect that we are in our fork of Mirador and/or that we are annotating an image canvas ?

**Comment by geourjoa** [comment]
@daxid  What is Document template ? 

I have not checked but I think we have no good way to detect ff we are in are in your fork with an image manifest.
Why do you want to do that ?

**Comment by geourjoa** [comment]
Not relevant anymore
