### ISSUE TITLE
Implement new interface

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-annotation-editor#32]
Implement new interface more on adequation with IIIF background 

https://penpot.tetras-libre.fr/#/workspace/4271200e-514b-8106-8003-9cd5f33c6c4f/45b8fe88-7525-810b-8003-f4704af3b2ae?page-id=4271200e-514b-8106-8003-9cdaa4e2ab6d

**Comment by geourjoa** [comment]
React Json editor : 

https://www.npmjs.com/package/rc-json-editor

**Comment by daxid** [comment]
@geourjoa What is this issue that is not linked with any EPIC or with anything ?

Please respect the basics of project management we are trying to enforce here.

**Comment by geourjoa** [comment]
All the epics and the issues in the board have not been updated since the UI change. We must recheck all the board

**Comment by geourjoa** [comment]
My view was here : https://github.com/orgs/SCENE-CE/projects/1
