### ISSUE TITLE
Post-Refacto-Bug

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#35]
TO FIX : 

- [x] button HMS input start / end broken
- [x] Input URL image
- [x] Can't write on manifest URL input
- [x] when drawing active space Target is still clickable and at foreground

**Comment by geourjoa** [comment]
Batch of a edits :

- [ ] TextComment Template
    - [ ] Placeholder RichTextSection 
- [ ] AnnotationFormHeader
   - [ ] Font style
   - [ ] Back button and Text align on the left 
- [ ] Target Form Section
   - [ ] Remove useless Paper or remove useless shadom   
- [ ] AnnotationTemplateSelector
   - [ ] Card Title in black bold style, Card description grey
   - [ ] Adjust Icone size and vertical alignment 
- [ ] Image field in imageTemplate
  - [ ]  On new annotation the field is already read 
- [ ] All annotation tempalte
   - [ ]  Increase margin size 
   - [ ] Remove all useless shadow border
- [ ] KOnvaTemplate
   - [ ]  Check all tool functionning
   - [ ] Don't display spatial target selection
