### ISSUE TITLE
Add media compatibily in template

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-annotation-editor#39]
In the template list, add a field for media compatibility 

- video
- image 
- sound

@Drilio here is a table of compatibility 

||Video|Image|Audio |
|--|--|--|--|
Note| ✅  | ✅ |✅|
Tag| ✅ | ✅ |✅|
Image| ✅ | 🟠 |🟠|
Overlay| ✅ |🟠|🟠|
Document| ✅ |✅|✅|
Expert| ✅ | ✅ | ✅ |

Legend:

✅ Yes
🟠 May come in the future

**Comment by Drilio** [comment]
Just a question, does the Image Template need a spacial target ?

**Comment by daxid** [comment]
Of course it does.

**Comment by geourjoa** [comment]
@daxid Audio spec is always relevant ?

**Comment by daxid** [comment]
@geourjoa Yes

**Comment by geourjoa** [comment]
Audio will be provided by video provider like Peer tube
