### ISSUE TITLE
Audio Media implementation

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#52]
# For now we choose to block the creation and the edition of annotation in audio media

## Audio Media must support those templates :
- [ ] Note
- [ ] Document
- [ ] Tag
- [ ] Expert Mode

**Comment by Drilio** [comment]
TimeTarget may be difficult to implement, Mirador doesn't use the same king of function in audioPlayer and in videoPlayer. 

What I'm trying to do : 

Reproduce the same comportment on audio and video =>  when Time of annotation change the player must follow.
 
What I Know : 

Audio is handled by pure Html using the `<audio></audio> `

**Comment by Drilio** [comment]
I'll try to use an 'old school' way to handle this case by getting html element with a dom selector in JS and try to use methods `like myAudioElement.play()` explain there : https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio

**Comment by geourjoa** [comment]
We will use peer tube to deal with audio media
