### ISSUE TITLE
Fix usability bug

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-annotation-editor#60]
After 15/03 meeting with DR

# Overlay 

- [x] Add title component  
- [x] Unable to change current object param
- [x] Show text tool in drawing mode 
- [x] Outil par défault rectangle 
- [x] Simplify Text Tool
- [x] Fix onTransform bug (weird comportment when resizing object)
- [x] Fix stroke scale problem

# Image 

- [x] #45 

# Target 

- [ ] #50 
- [x] SHow transformer on selected shape 
- [x] Fix "red" shape bug. 
- [x] Fix saving drawing state. The drawing state muste be set to false 
- [x] Block rotation in target shape 
- [x] Outil par défault rectangle 
- [x] Add dash in target shape

# Global

- [x] Fix order of template 
- [ ] #61

**Comment by Drilio** [comment]
text tool should have this comportement : https://codesandbox.io/p/sandbox/react-konva-editable-resizable-text-55kyv?file=%2Fsrc%2FEditableText.jsx%3A8%2C17

**Comment by geourjoa** [comment]
Replace with more up to date meta issue : https://github.com/SCENE-CE/mirador-annotation-editor/issues/111
