### ISSUE TITLE
Use correct origin when saving the target from an annotation 

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#77]
When we create an annotation the target origin is set from the top left of the viewer but it should be set a the top left of the media.

**Comment by Drilio** [comment]
![Image](https://github.com/SCENE-CE/mirador-annotation-editor/assets/117070163/5fc52e29-0fee-4de1-acf6-5f3e27dae704)

**Comment by Drilio** [comment]
![Image](https://github.com/SCENE-CE/mirador-annotation-editor/assets/117070163/5a1aa033-4e70-4d77-bb7e-8b43a3458171)

**Comment by geourjoa** [comment]
Fixed in #86
