### ISSUE TITLE
Display correctly target, the origin position is not placed correctly with video

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#78]
When displaying a target on an image the origin is taken from the top left of an image.

When displaying a target on a video the origin is taken from the top left of the viewer it should be taken from the top left of the video.

this should be fixed in Mirador Video.

**Comment by Drilio** [comment]
https://github.com/SCENE-CE/mirador-annotation-editor/issues/77 the fix for this issue fix the problem for the video

**Comment by geourjoa** [comment]
Fixed in Mirador Video in 1.0.12
