### ISSUE TITLE
Encapsulate AnotationDrawing and AnnotationFormOverlay into a Konva Component

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#82]
Encapsulate AnotationDrawing and AnnotationFormOverlay into a Konva Component : 

- [ ] pass only in props :
 - DisplayMode
 - DrawingState/SetDrawingState
 
- [ ] set DeleteShape and UpdateCurrentShape into that component

- [ ] Clean duplicate code into TargetSpatialInput, DrawingTemplate, ImageCommentTemplate

**Comment by geourjoa** [comment]
Not relevant anymore
