### ISSUE TITLE
Fix scale problem when saving string target or image in TaggingTemplate

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-annotation-editor#86]
The Konva Stage is wider than the image media, here I applied a blue background on the konva's stage : 

![Image](https://github.com/SCENE-CE/mirador-annotation-editor/assets/117070163/949ae9fe-a85d-438f-a79c-695d8edb76a4)

This situation results into this bug : 

1) I create a target there : 

![Image](https://github.com/SCENE-CE/mirador-annotation-editor/assets/117070163/e55e41f6-704b-4ddf-b4ed-18c375ec2a3e)

2) it's displayed there : 

![Image](https://github.com/SCENE-CE/mirador-annotation-editor/assets/117070163/d69f6b8d-29e4-47b2-9388-aad3e6966803)

**Comment by Drilio** [comment]
We may find a method displayed by OpenSeaDragon that could give us the position and dimenssions of the image in the doc : https://openseadragon.github.io/docs/OpenSeadragon.html

**Comment by d-flood** [comment]
https://github.com/SCENE-CE/mirador-annotation-editor/assets/69060117/861ed89e-8bbd-4068-836d-c7792609d812

I finally made some progress here. I've got the Konva `Stage` to stick with the IIIF image. I tried quite a number of things but my final solution is both simple and hacky—hopefully you have some suggestions.

**Comment by d-flood** [comment]
My solution won't work. The Konva Stage needs to be pinned to the IIIF Canvas, not to the image.

**Comment by daxid** [comment]
This looks promising ! Congrats @d-flood 

However when you save the annotation, it is displayed in the wrong place.

**Comment by d-flood** [comment]
That's right, the scaling is still off. You can see this when drawing the rectangle; the further you drag to the bottom left the less accurate when rendered. However, the Konva drawings are _internally_ consistent. When you edit an annotation, it will be drawn in the same place you placed it originally. 

I am guessing that we have to set the scale for the Konva overlay to the OSD reported zoom and not a Mirador reported zoom.

**Comment by geourjoa** [comment]
--------------BZP5nGFBb5koIDEQ22zbKDmn
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit



  

    
    
  
  
    Bonjour,
      
      Je suis indisponible du 15 juillet au 11 aout. Je prendrais
      connaissance de votre message Ã  mon retour.
      
      Durant cette pÃ©riode vous pouvez contactez ***@***.***
      ou ***@***.*** si
      nÃ©cessaire.
      
      Bonne journÃ©e,
    
    -- 
      
        
          
            
              
              
              
            
          
          
            
            
              Anthony Geourjon
              AssociÃ©, co-gÃ©rant
            
          
          
            
              
                ***@***.*** / 0632189416
                http://www.tetras-libre.fr
                13
                    rue Martin Luther King, 38400 St Martin d'HÃ¨res
              
            
          
        
      
    
  

--------------BZP5nGFBb5koIDEQ22zbKDmn
Content-Type: image/png; name="PpvNmeNA0dRoam7n.png"
Content-Disposition: inline; filename="PpvNmeNA0dRoam7n.png"
Content-Id: 
Content-Transfer-Encoding: base64

iVBORw0KGgoAAAANSUhEUgAAADQAAAA8CAYAAAApK5mGAAAABHNCSVQICAgIfAhkiAAAAAlw
SFlzAAABJgAAASYBX/sSKAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA
ABLsSURBVGiB1Zp5XFRHtsd/9/beDc3S3SpIBAQaBBQkGoi8KCJjos4wUSZqHBf4BJd5xkny
3nN5mehIkhcnwX2yjBrDi4ZknkRDRkMI+lSMSyTGKCHKKsjWINDQ6226b9+aP6CxabpZ3iz5
vPP5dPe9detUnW+dqlN1qxr4+0q8Wq2+5u/v/z2ANAD037n8f7rISktLP+I4rmP58uVfqdXq
M5mZmXkA0n9qw8YqgQCyAagVCsUSvV5/m+O4zr179/4PIYTNy8srBpD8E9s4eklISMjt6en5
7tatWyVz587dGxMT84ndbm/r7Oy8bjKZbnMc1+Ht7b35p7ZzLPKHK1eufE4IYQkhTH5+fmFG
RsYVQoilurr6NCGEzcrKeuWnNDBqLJmnTZtWQAgx9wOxhBC2tLS0OD8/v9hkMpURQjpyc3Nz
/1HGOounKPTEWAopLy//cMaMGbsOHjx4SK/XfwcAs2fPTmMYplcikTwCQGixWEK8vLx2AFD8
jTYPK5TLvS8APwDLAfzZg04DAOKkv2/p0qWRGzZs4AQCgaC8vNz65JNP0mFhYfMBsIQQK0VR
0qKiotMpKSkTZTLZ5wD+6x/AMmCQs4QCmOzj45OxbNmyakIIoSiKomma4jiOcBzH7d2796a3
tzcLgPvtb38bvWnTpjURERGzXcohLvewWq1NQqFQFRIScqihoeGPADg3HwLA7nJN3OWlKGpI
HQDAd7mvB1CvVquTDx061NuvbHeqxA5gkiNt0aJFApPJJHEo6/X6Go7jen18fIIoivJ1Llgo
FE4ymUzVSUlJ1QC8nYyze6hnuDS2/9dVwlyBAAAikUgIgIfBHnT1Jt54440ni4uLfQCgvb39
jq+vr1wkEkW4KxMATp06ZdTr9T79ZTvLQNn6J9Of7m1o/PkdPn13+oSAG/L//eJLN3U7wJyF
BrDAtWAAoKOjo9NWrlxpdqlsCFxHR4e1qKhI2dzc3BQXF+ctlUone4IBgGnTpsknTpzodeHC
hdvTp083uSuzaUfO/i6zOaFcp02aqDemSELCjvGnqG0u+ew5OTmuQM8AOOfOQ/4BAQFWPGzF
IZ5xpG3ZsqUOQE1ycvLGrKysYWEAgKIo2Zw5cyJPnz49AcADV6CIiIh19xpqI5Lj4ymu1Yyq
xQskbGnJhANLFplc6na1SYi+YNbkLmyrwsPDHUCePrTz/fr16wFAMBIQANA0LdfpdD/TarVC
53I2bdoUU1tb+xIHUF/fugXfmTNw84cfSmJiYgxu6naVlQAK4OGhUq1Ws56Mdwd38uRJLcuy
mtEAARAfOXLkZ5s3b95y9+5dGQCeTqcTHD9+fDOcWr6kpMQ+adIk73Xr1rkCuQ4Tn/5frScg
VUxMDPEA4hZOoVCY+Hy+H8uyWgBmN2UOEpqm/Y8cOZLa0dHxYk5OTnR4ePh+nU430zmPQqEo
+PDDDzd4qNs5ZK+E05zpbgz5RkREOJQ9jh9nCQ4O9mFZtvfs2bMNCxYsSBgJSK/X13388cc9
ubm5Sffu3VvsLs/mzZvfh+doyPX/BgDohFMjDgHi8Xg8Pp8v6VdyF7aHpN24ccP3888/r8vI
yIgcDsRisbSuXr3aWFBQ4HGtGBkZierqavv8+fN1eNiDXOt2eOhZAAed9Yd0OblcLkIfqMND
I3a7pKSksrq6Om8AMg92kqtXr5arVCrlcDAAsGzZMhBCeLm5udPc1Oe4dnjoC/RNsp6BfH19
RR4API6p+fPnt8fFxfV6sNGek5NTmZycHG80GsXDwQDA/v37AQDl5eWxTvU4NyzltOypctUf
AuTt7S1yY/ywkW7mzJlGrVbb48Y+snPnzrqdO3fGjATikPj4eABAd3d3qAcb3K7hPALJZLJB
HtJqtY57GsN4q7Cw0MAwTJtzWd988011Tk7OmN6tsrOzAQBGozHATT303wS0Y8eOqe+//37Y
kiVL5rmBGtRyq1evvl1TU9PlVBS3du3acWOBCQ0NBSF99nIcJ3GuZ82aNTMmTZr0O5VK9RqA
eE9lDIlyMplMiv5ownEc/80330xjWZa3atUq6+LFi2vS09M1fD6fdVGjFi1a1JWammoqKipq
E4vFE9ra2hoqKirCxwIklUqRlZUFAEhPT+d99NFHuwoLC3saGxsb33rrrcQPPvggSKPRPJg0
adKx8PDwxnHjxo1/8OCBuaam5gSAd+HGe+LMzMyDhJB3CSF/7Onpecff31/fn5EoFIruuLi4
qtbW1l2EkB2EkO2EkJcJIdsIIZsrKyu3b9u2rZwQYt+0aVOVQ280n4ULF5Lf/OY3A/ft7e1V
hBA7IcTOMEwTIcRICLFbLJb7LMs2EkKY3t7eu3a7vf3w4cMlAFYBQyeugKeffjopJSVFBABi
sZhMnTq1qbm5ma/RaHyNRqOsvb1d8fHHH6v5fL7ex8enV6VSOVbClFKptOn1+naapkVr1qyJ
hfuJeYjEx8djy5Yt2L59O2w2G/bs2XMzLS0t2vGcz+d7o3+tyOfzvSmKIhzHaQUCQWhnZ2fl
zp07xfX19a/CzSol4fjx43sJIe8TQg71e+ptQsiBK1eu5M2ZM6dCKBT2urYun8+3CYVCCwDi
4+NjkkgklrF4x9fXd+B6xYoVNRzHMQ7vuPnYCCFWu92uaW1tvUIIsTIMU61QKF4BhgYFZWRk
pLuBz5s1a5b+4sWLZ7Va7bvHjx//5Be/+EWZXC430DTNqVSq3u3bt3e0trbW9/T00Lm5ufdH
4xmH9PT0Rfzs7Oyq/Pz8AIqihJ7yMgxzr7Gx8VuGYbQTJkyIKSwsvNDU1NSWnJzsdrz+WqvV
vk0I+ZAQktfvqcOEkPf6PXWQELKPELK7rKzsUFRUVP1bb73VwHGcwbkVv/zyyxqlUmkarYdo
muaOHj1aTgixDuMZOyHEXlpaeo4QYsvOzr5sMBjKOY7TpqamXoKH3aS1hJD/JoR8RAg55gbq
HULIwd27d//liSeeaG9vb28ihHAuHzshxL5jx457I4EEBgYat23bVv3gwYN7w0E4uqDFYmmc
MmVKDSHE3NjY+E1oaOgFlmUbzWZzFYC1Q2ikUukGQsgJQsgnLlBHHVD79+8vWr58uYbjOJMb
GGcoi16vb05MTGwCQEQiEbtkyRLN0aNHa6qqqmqsVuuDkbxBCLG3tLTc5TjOSAjpLSgouC4Q
CJ4rLi4usdlsTQA2paamfmYwGG4B2A24zEMKhUKKwZFvSJQ6duxYbH5+fi+Gf0OlAAiEQqGo
oaFBFhoaWn/hwoW87u7u0NDQ0Hk+Pj5Bw+g6xF5RUXEnKioqsKWlpV4ikUjy8vK+t9lsR5cs
WRKydetWIYB758+fL1MoFJsAvD3E4NjY2P/84YcfHsMwW0l2u528+eabISUlJRErVqwgGRkZ
AoVCoUDfez0AgBDSe/v27eaFCxcG+Pv7N1+8ePETpVJpAWBfuHDhr7744otoiqI8rsxrampq
33vvvR97enqai4uLf75t2zbDmTNn7pSUlHxAUdS5/nzhAGrdteSAJCcnv3r58uV4dyCuaRzH
2b/66iv/kydPPnL//n15UFCQqK2tTdnR0cG/c+eOgGEYYVpa2renT58uEovFrEP//PnzfufO
nVv0wgsveItEIsKyLG2xWGzNzc22ysrK3q+//rp55syZ1zds2FAHgNNoNDyapu3jx4+3AOim
KKp0OLcOAlqwYMHuoqKiKR6ABq5PnTqlXLduXUpXV9eQVpbJZObExMTa7OzsW88++2yTk65j
J9TOMAzOnj3rLxKJWJvNxnV2dgqioqK6k5KStCPU3UZR1JXhgAaNIZlM5lgQeoKmamtrJZmZ
mWkGg0EEACKRyJaVlfXdvHnzmiMjI/VTp07VORniPM85XsogkUi49PT0TgztAcPWDZeXuZGA
KBcgt/sJr7/++hSDwSAKDg7ulkql1ry8vEuJiYndozTKk6HDPXdOs7qlcBJnIL+goCDHm6HH
SpOTk7Vqtfqbl19+uQ4Pu8OwOmNI87hv0S/OO6huxRlIGRoa6gzkttK1a9e2Y2h3+lsNHW3a
mIBUkydPFuCfZyg3wnN3aWPqcsrJkyeLMXg/jmpubhZWVlYKjUYjNX78eEtCQoK+qalJXFlZ
KWYYBoGBgeaEhATdjz/+6H3//n0hTdNcWFiYITY2VldcXKzSaDTCmJiY7qSkpG5Hmfn5+RM7
OzsFL7zwQg0AWK1W3qeffjrRYDDw5s6dq1Gr1Qa4aaTo6OiFAN4ZDshZKctmsz3L5/N94BQu
V61aFdbV1cWrqKiQR0ZG6jdu3Fi/devW6NjYWK1QKLS3trZKnn/++ao9e/ZE6XQ6vpeXl5Wi
KPLZZ59dmD59+uKUlJTahoYGn/Hjx+tPnz593mAwUNHR0b8mhJAzZ878OT4+vketVq9RqVRa
uVxuunXrVnhubu6JlStX3ofLHBgYGCjRaDT7RwXE4/HWsiy7Fn1dblA4bWlpoTdu3Di5sLCw
AoD9sccem1FWVnbNNd/WrVvDpkyZosvMzGxubW3lL1269PHLly+fBWAPCwvLqKioOPGnP/1p
UllZ2biQkJDuzs5O8ZEjR66GhIRkNjQ0HAHA1dXVCQMCAixSqdQKl3nI39+f6u7uHtZDA12u
fz9OjIcHSc7jg8bDvTF0dXWJAgMD5wHAc889V/vaa6/VAgBFUTRFUQM7QxRFUQB4LS0tIpZl
eRKJhHr11VfneXl5MdeuXePa2tr8XnrppQqBQMBFRUWtAQCj0SjOyMi4fuDAgevOhnIcRxuN
xhH3zQeAVCqVl7PRGNwdeQ7jAECpVFqvX79+Ay5hm6ZpBxANgHfz5s2JsbGxP+/u7pbMmjXr
PgBeQECArry8/CSfz7dPmTIlQ61W9x4+fLh47ty5DwBwmzdvnmo0GgWudlRWVtI2m6151EB+
fn6OSZVzzURRlAOIBgCdTidMT0+fBoC0traKdu/efSclJUXbl7XPQxRF8R599FHNpUuXLppM
JmrWrFlpAHgCgYDj8/l0f8OYGxsbZVu2bEmx2+2UXC433717d+KBAwdOuQESAOgYNZCvr68M
Q08cKABQqVTcrl27Wh3PL1++XF5dXS3o7e1FYGAgo1arzQB469ev18hkMhsAnkql4g4cOFAO
gCeTybhDhw5dA0AfPnz4iqOct99++9q4cePYb7/99vTVq1e9u7q6BI8//vhX/SvzQdsDdXV1
IvSdNIwOyNvb2wE0RAQCASIjIx2HYJRSqbQrlUoGLmu24OBgFn2LUB6fz7dPnz6dcegkJSWZ
APASExNNjnri4uIcY4I3a9YsAwYvnwY1bGNjo3isQF5wM35OXDvjI5fK2afiZuucFd8t+WhC
XmlBoLmX4UmEYvaZpEVNW9PX19++f9cr+/C2RymKIjRFczt/9eLNp+JmtwPAEzlLF9jsLEUR
iixKSK16ZfHGCgBYsmfD/IaOZiVF0RzLsfQby/7jzKKE1BZnII1GI0b/Kd1ogER+fn6OSXUQ
UIdeK+Tz+I4TvYEKVj7xS+2/zl/Z9vSeddGF/374to4xUAB4OrNBmDY1WbNr+ZbKy5Xfyj8o
/TT4qbjZnQAoMV/Efv37E2ctNivmv7Fq/jNJixojA0L0WrNOdvMPZz4BYLexLLHYeoHBXrIz
DOPpvwlugZQhISHuzi/7hvnDyDUQyuUS7/7o1hf9fPrvKYD31e1LQTWtDfK6jiavhfFzGh8a
15dXLBBy/l6+DGM1CwDwrKxNMPe1FYsJCPlZ7L9U/m7xxh9cgGC1Wkdcx7kCOTbpB1D6v2hg
YG7hvm+4I54eEj1wzE5RLqGeouiZYXFdLy7Mqm/q0vB/X7AvFkA1AGhN3dLn836f8EDXKekx
6yXTHokyAeAJeQJu3+pXLgHgxnkrGLhpWLPZPCYgVXBwsBRuFqYURVHXqr+X2Vgb1Wu3kr/c
OCcvePGd+uJbpfImrYbXaegRfHCxYLzC28/6y0fTuihQtM5sEDZ3aSR3W+qkYoF4YJ7yEktt
qTGzOhTevpbtJ/bG0zTNA0BxhKMvV92YIOKJbK097ZKn4uY0JobHdTnbwTAMMxogR0s8tmvX
rnlisdgPLtHFRyq3t+s7+C3aNr7VztJPz5yvD1EF2YwWM13ZWitWyRU2lrNTsY9EMEH+AVaJ
UMzd72gWfnevwpdP88hrz/xblVzqxQGA3mxCVsqvWkJUQYzWqKNmhsX18Gia8Hh8S5Wm3rdV
q/ESCoRccuSMDj+Zj+PtlAKAffv2Gbq6uoZ9/R7IDCCbELIdfWf+o/0DkfM+wbB7EGNI8/g8
MDCwcaSFKdDf5QQCAY2+rVTn/8E5/7peO2TIqmIUOv+ndyyDweDpDHeQ8AFg3Lhx0v5rh4F/
z32AYQ0dTTlms5liGMbkJq9b5Wwej5eSlJR0z5HIcdygkzDSf07oKd1ZHHlGW4bzvclksrIs
O8TrDMPIOzs7/QF8B+DYaMCyR5PpJ5Q4ADNHzIX/P3/lV2IU6zgA+CumSJsh1VZN7wAAAABJ
RU5ErkJggg==

--------------BZP5nGFBb5koIDEQ22zbKDmn--

**Comment by d-flood** [comment]
Some progress. I've refactored (again) the zoom calculation and use that calculation for the scale. This is much closer.

- We have the correct origin: 0,0 is the top left of the image.
- The size and positioning of the annotation is much closer now, but still not right. No the position is a little too far from origin, but only when rendered by Mirador. The position remains correct when editing and viewing the Konva layer.

https://github.com/user-attachments/assets/c8d38300-47ab-4828-a59a-2e5c75272c37

**Comment by daxid** [comment]
Hi @d-flood 

@geourjoa made good progress on the scaling in the branch https://github.com/SCENE-CE/mirador-annotation-editor/tree/86-stage-canvas-fix-scale

The correct scale to apply is the product of 3 scales but we had only 2 previously.

The reopening  of an annotation for edition is now broken (as expected) but @geourjoa will fix it.

**Comment by d-flood** [comment]
I checked out @geourjoa's branch; it was very exciting to see that annotation rendered at correct location and size! This is encouraging progress.

**Comment by geourjoa** [comment]
I have done some progress 

On 86-fix-konva i have been to generate the good SVG. I have done some step manually

1. Dont use KOnva drawing stage but a static stage with 4 rect (See Annotation Drawing at bd35ec40dfaaec8d90e8a995984ab92c78df4b40 for example 
2. Open annotation edit tool and select target template 

![image](https://github.com/user-attachments/assets/b1e40b20-caed-416e-9451-de9b018c1d84)


3. Resize Stage to image true width. Done by calling this function with a debug button
```
 const resizeStage = () => {
    const { stages } = window.Konva;
    stages.forEach((stage) => {
      console.log('Stages', stage.toJSON());
    });
    const stage = window.Konva.stages.find((s) => s.attrs.id === windowId);


    let scale = 1/playerReferences.getScale();

    stage.width(playerReferences.getWidth());
    stage.height(playerReferences.getHeight());
    stage.scale({ x: scale, y: scale });

    stage.draw();
  }

```
![image](https://github.com/user-attachments/assets/79451779-bbf5-40cc-b41e-52ca908d6442)


4. Export the svg by clicking on the Export SVG button. SVG is displayed in console.log

5. Save the annotation 

6. App is crashing because SVG saved is broken. 

7. Open localstorage data (we are using localstorageadapter in dev) and manually change the broken SVG by the SVG exported manually. 

8. reload the page. 

![image](https://github.com/user-attachments/assets/222c32aa-2bc2-4829-a4a4-3c10416278b8)





Rond à la main

**Comment by geourjoa** [comment]
Exported SVG Manually 

<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="400" height="400"><defs/><g><g><path fill="red" stroke="none" paint-order="stroke fill markers" d=" M 0 0 L 59.523809523809526 0 L 59.523809523809526 59.523809523809526 L 0 59.523809523809526 L 0 0 Z Z"/></g><g><path fill="red" stroke="none" paint-order="stroke fill markers" d=" M 340.4761904761905 0 L 400 0 L 400 59.523809523809526 L 340.4761904761905 59.523809523809526 L 340.4761904761905 0 Z Z"/></g><g><path fill="blue" stroke="none" paint-order="stroke fill markers" d=" M 340.4761904761905 340.4761904761905 L 400 340.4761904761905 L 400 400 L 340.4761904761905 400 L 340.4761904761905 340.4761904761905 Z Z"/></g><g><path fill="red" stroke="none" paint-order="stroke fill markers" d=" M 0 340.4761904761905 L 59.523809523809526 340.4761904761905 L 59.523809523809526 400 L 0 400 L 0 340.4761904761905 Z Z"/></g></g></svg>

**Comment by geourjoa** [comment]
In MAEV the SVG is created but not displayed.

The IIIFTempalte is break so no option to edit easily the target in maev
