### ISSUE TITLE
Fix position on video viewer and target

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#90]
- [x] Fix position on video viewer and target with vertical video Chromium
    - [x] Full screen
    - [x] With left companion window opened
    - [x] With annotation form window opened 
    - [x] On resize 
- [ ] Fix position on video viewer and target with vertical video  Firefox
    - [ ] Full screen
    - [ ] With left companion window opened
    - [ ] With annotation form window opened 
    - [ ] On resize 
- [x] Fix position on video viewer and target with landscape video  Chromium
    - [x] Full screen
    - [x] With left companion window opened
    - [x] With annotation form window opened 
    - [x] On resize 
- [ ] Fix position on video viewer and target with landscape video  Firefox
    - [ ] Full screen
    - [ ] With left companion window opened
    - [ ] With annotation form window opened 
    - [ ] On resize 
   
- [ ] Optimize the display of video in Firefox 

![Image](https://github.com/SCENE-CE/mirador-annotation-editor/assets/122985699/3bec2ae9-177e-47ed-9948-18315e347a16)

- [ ] Keep the optimize display of video in Chromium
- [ ] Add default manifest in sample : https://files.tetras-libre.fr/dev/multicanva-video.json

**Comment by Drilio** [comment]
## Fix position on video viewer and target with vertical video Firefo 

This come from the css applied on _<canvas>_ [there](https://github.com/SCENE-CE/mirador-video/blob/6b8f20ae58a03df7b5db101f8371073be8f1720b/src/components/AnnotationsOverlayVideo.js#L629).
We just need to remove the `left:0`

**Comment by Drilio** [comment]
# Fix position on video viewer and target with landscape FIREFOX AND CHROME

We introduced a regression at some point : 


![Image](https://github.com/SCENE-CE/mirador-annotation-editor/assets/117070163/57fff9e9-a5dc-4944-ac40-c433fe12a26a)

**Comment by geourjoa** [comment]
Fixed in #86
