### ISSUE TITLE
Mirador Crash when multiple target on Images

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor#96]
![Image](https://github.com/SCENE-CE/mirador-annotation-editor/assets/117070163/68e7a100-7d6d-4665-baad-caa089a9f91b)

this error happens when you set multiple spatial target on images.

App lags with large images and so the target drawing lags too and it can lead to multiple target drawing and make you run into this bug without event noticing it

@geourjoa is a know bug and what should be the comportment of the app in this case ?

**Comment by geourjoa** [comment]
Bug from broken export of the SVG. Fixed in #86 in tagggingTemplate
